[package]
org = "medi_find"
name = "medi_find_backend"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
keywords = ["medicine", "pharmacy", "healthcare"]
repository = "https://github.com/yourusername/medi-find-backend"
license = ["Apache-2.0"]
readme = "README.md"

[build-options]
observabilityIncluded = true
